FROM python:2-onbuild
MAINTAINER jpatel@pivotal.io

WORKDIR /usr/local/
# RUN git clone https://github.com/dbbaskette/cape.git
RUN git clone https://github.com/jpatel-pivotal/cape.git
WORKDIR /usr/local/cape
#ENTRYPOINT [ "python", "cape.py"]
#EXPOSE 22

#cmd ["ls"]
